name: Download and Build Mirror

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror download page
        run: wget --user-agent="ByondBuildMirror/1.0" -r -np -k -p https://www.byond.com/build/

      - name: Upload download page as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: byond.com/

  deploy:
    permissions:
      pages: write
      id-token: write  

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4