name: Download and Build Mirror

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Restore cache
        id: restore_mirror_cache
        uses: actions/cache/restore@v4
        with:
          path: www.byond.com/
          key: byondmirror-

      - name: Mirror download page
        continue-on-error: true
        run: wget --user-agent="ByondBuildMirror/1.0" --wait 7 --random-wait --include-directories="download/build/516","download/build/517","download/build/518" -r -np -k -N -p https://www.byond.com/download/build/

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: www.byond.com/
          key: ${{ steps.restore_mirror_cache.outputs.cache-primary-key }}

      - name: Upload download page as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: www.byond.com/

  deploy:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
