name: Download and Build Mirror

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # `actions:write` permission is required to delete caches
      #   See also: https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-a-github-actions-cache-for-a-repository-using-a-cache-id
      actions: write
      contents: read

    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: www.byond.com/
          key: byondmirror-
          restore-keys: |
            byondmirror-

      - name: Mirror download page
        # continue-on-error: true
        # run: wget --user-agent="ByondBuildMirror/1.0" --wait 7 --random-wait --include-directories="download/build/516","download/build/517","download/build/518" -r -np -k -N -p https://www.byond.com/download/build/
        run: |
          rm -r www.byond.com/
          wget --user-agent="ByondBuildMirror/1.0" --wait 1 --random-wait --include-directories="byond-build-mirror/download/build/516","download/build/517","download/build/518" -r -np -k -N -p https://cmss13-devs.github.io/byond-build-mirror/download/build/
          mkdir www.byond.com
          mv cmss13-devs.github.io/byond-build-mirror/download/ www.byond.com/download/
          rm -r cmss13-devs.github.io/

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: www.byond.com/
          key: byondmirror-${{ github.run_id }}

      - name: Cleanup old caches
        continue-on-error: true
        run: |
          cacheKeys=$(gh cache list --key byondmirror- --json key --jq '.[].key')

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          for cacheKey in $cacheKeys
          do
            if [[ $cacheKey == $LATEST ]]; then
              continue
            fi
            echo "Deleting $cacheKey"
            gh cache delete $cacheKey
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          LATEST: byondmirror-${{ github.run_id }}

      - name: Upload download page as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: www.byond.com/

  deploy:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
